# Generated by Django 4.2.23 on 2025-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contactno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
